version: '3'

services:
  database:
    image: postgres:13-alpine
    container_name: shopping-list_database
    env_file:
      - ./.db.env
    ports:
      - 5432:5432
  
  api:
    build: ./api
    container_name: shopping-list_api
    command: >
      sh -c "alembic upgrade head && 
             uvicorn --host 0.0.0.0 --port 8000 --reload shopping_list.main:app"
    volumes:
      - ./api:/usr/src/app
    env_file:
      - ./.dev.env
    ports:
      - 8000:8000
    depends_on:
      - database